site_name: Programming Practices for Research in Econonomics
pages:
- Welcome: index.md
- Windows Subsystem: windows-wsl.md
#- Terminology: terminology.md
- Command Line Tools: commandLine.md
- Text Editor: textEditor.md
- Git: gitInstall.md
- Python: python.md
- Python Extras: python-more.md
- Webscraping: webscraping_drivers.md
- Automation with Snakemake: snakemake.md
- R: r.md
- LaTeX & Pandoc: pandoc.md
- The Finish Line!: finish.md
- Contact Us: contact.md
- Citation & License: citation-license.md
- Acknowledgements: acknowledgement.md

theme: readthedocs
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
